version: '3'
services:
  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - './docker/volume/mysql:/var/lib/mysql'

  php:
    build:
      context: ./docker/php
    volumes:
      - "./:/var/www/html"

  nginx:
    image: nginx:1.25.1
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html"
      - "./docker/nginx/conf:/etc/nginx/conf.d"
